# Generated by Django 5.1.5 on 2025-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedetail',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
