# Generated by Django 5.1.5 on 2025-01-29 15:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_created_supplier_modified_termin_created_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='termin',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='termin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.termin'),
        ),
    ]
