# Generated by Django 5.1.5 on 2025-02-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_managers_alter_termin_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='termin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.termin'),
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='suppliers',
        ),
        migrations.AlterModelTable(
            name='termin',
            table='termins',
        ),
    ]
